/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * crypto alert
 * OpenAPI spec version: 1.0.0
 */

export interface Alert {
  _id: string;
  createdAt: string;
  currentPrice: string;
  differencePrice: string;
  price: number;
  reachedAt: string;
  status: string;
  symbol: string;
}
