/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * crypto alert
 * OpenAPI spec version: 1.0.0
 */
import type { Alert } from './alert';
import type { GetAlert200ItemAllOf } from './getAlert200ItemAllOf';

export type GetAlert200Item = Alert & GetAlert200ItemAllOf;
