/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * crypto alert
 * OpenAPI spec version: 1.0.0
 */
import type { Alert } from './alert';

export type GetAlerts200 = {
  data: Alert[];
  /** @nullable */
  nextPage: string | null;
};
