/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * crypto alert
 * OpenAPI spec version: 1.0.0
 */

export type GetAlert200 = {
  _id: string;
  createdAt: string;
  currentPrice: string;
  differencePrice: string;
  initialPrice: string;
  price: number;
  reachedAt: string;
  reachedPrice: string;
  status: string;
  symbol: string;
  target: string;
};
