/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * crypto alert
 * OpenAPI spec version: 1.0.0
 */
import type { GetCrypto200AnyOf } from './getCrypto200AnyOf';
import type { GetCrypto200AnyOfTwoItem } from './getCrypto200AnyOfTwoItem';

export type GetCrypto200 = GetCrypto200AnyOf | GetCrypto200AnyOfTwoItem[];
