/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * crypto alert
 * OpenAPI spec version: 1.0.0
 */
import type { GetCryptos200DataItem } from './getCryptos200DataItem';

export type GetCryptos200 = {
  data: GetCryptos200DataItem[];
  /** @nullable */
  nextPage: string | null;
};
