/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * crypto alert
 * OpenAPI spec version: 1.0.0
 */

export type GetCrypto200AnyOf = {
  price: string;
  symbol: string;
  updatedAt: string;
};
