/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * crypto alert
 * OpenAPI spec version: 1.0.0
 */

export type PostAlertBody = {
  /**
   * Price to buy the coin
   * @minLength 1
   */
  price: string;
  /**
   * Symbol of the coin
   * @minLength 1
   */
  symbol: string;
};
