/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * crypto alert
 * OpenAPI spec version: 1.0.0
 */

export type UserNotification = {
  /** Email notification enabled */
  email: boolean;
  /** Push notification enabled */
  pushNotification: boolean;
  /** Phone notification enabled */
  sms: boolean;
};
